src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJdbcStatement.java
src/test/java/io/vertx/ext/jdbc/JdbcServiceTestBase.java

PR to fix issue #10 Column labels are ignored in the ResultSet

Fix #10 Column labels are ignored in the ResultSet

---

pom.xml
src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/groovy/io/vertx/groovy/ext/jdbc/JDBCClient.groovy
src/main/java/examples/Examples.java
src/main/java/io/vertx/ext/jdbc/JDBCClient.java
src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/main/java/io/vertx/ext/jdbc/package-info.java
src/main/resources/vertx-jdbc-js/jdbc_client.js
src/test/java/io/vertx/ext/jdbc/JDBCClientTestBase.java

rename sql to SQL

---

src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java

Fixes #52: add support for types not declared on the JDK itself

---

src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCallable.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCExecute.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCQuery.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCUpdate.java
src/test/java/io/vertx/ext/jdbc/Functions.java
src/test/java/io/vertx/ext/jdbc/JDBCQueryTimeoutTest.java

Fixes vert-x3/vertx-sql-common#14

Fixes vert-x3/vertx-sql-common#14: Support query timeout

---

.github/ISSUE_TEMPLATE.md
pom.xml
src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/asciidoc/ruby/index.adoc
src/main/generated/io/vertx/rxjava/ext/jdbc/JDBCClient.java
src/main/groovy/io/vertx/groovy/ext/jdbc/JDBCClient.groovy
src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCAction.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCAutoCommit.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCallable.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCClose.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCommit.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCExecute.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCQuery.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCRollback.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCUpdate.java
src/main/java/io/vertx/ext/jdbc/package-info.java
src/test/java/io/vertx/ext/jdbc/Functions.java
src/test/java/io/vertx/ext/jdbc/JDBCClientTestBase.java
src/test/java/io/vertx/ext/jdbc/JDBCCustomTXIsolationTest.java
src/test/java/io/vertx/ext/jdbc/JDBCCustomTypesTest.java
src/test/java/io/vertx/ext/jdbc/JDBCQueryTimeoutTest.java
src/test/java/io/vertx/ext/jdbc/impl/actions/OptimisticCastTest.java
src/test/java/io/vertx/ext/jdbc/impl/actions/SQLConvertTest.java

Fixes vert-x3/vertx-sql-common#21
The client implementation of the API

Fixes vertx-sql-common#21: Implement the isolation level API

---

src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/main/java/io/vertx/ext/jdbc/spi/DataSourceProvider.java
src/main/java/io/vertx/ext/jdbc/spi/impl/BoneCPDataSourceProvider.java
src/main/java/io/vertx/ext/jdbc/spi/impl/C3P0DataSourceProvider.java
src/main/java/io/vertx/ext/jdbc/spi/impl/HikariCPDataSourceProvider.java
src/test/java/io/vertx/ext/jdbc/JDBCPoolMetricsTest.java
src/test/java/io/vertx/ext/jdbc/TestDSProvider.java
src/test/java/io/vertx/ext/jdbc/spi/impl/HikariCPDataSourceProviderTest.java

Expose data source usage metrics - fixes #59

---

src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCAction.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCAutoCommit.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCBatch.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCallable.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCClose.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCommit.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCExecute.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCQuery.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCRollback.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCUpdate.java
src/test/java/io/vertx/ext/jdbc/JDBCBatchTest.java

see: vert-x3/vertx-sql-common#22
Implemented batching support for jdbc clients (tests included)
Depends vert-x3/vertx-sql-common#22

Implement batching

---

src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/asciidoc/ruby/index.adoc
src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCAction.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCBatch.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCallable.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCExecute.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCQuery.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCUpdate.java
src/main/java/io/vertx/ext/jdbc/package-info.java
src/test/java/io/vertx/ext/jdbc/impl/actions/OptimisticCastTest.java
src/test/java/io/vertx/ext/jdbc/impl/actions/SQLConvertTest.java

disable optimistic UUID cast by default

---

src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
src/test/java/io/vertx/ext/jdbc/SharedClientTest.java

@pmlopes @cescoffier @tsegismont please review

Shared JDBCClient deadlock - fixes #69

---

src/test/java/io/vertx/ext/jdbc/CloseTest.java
src/test/java/io/vertx/ext/jdbc/ConfigFactory.java
src/test/java/io/vertx/ext/jdbc/JDBCCustomTypesTest.java

Two commits fixing the remaining (known) issues in the JDBC client test suite.

Intermittent failures in CloseTest and JDBCCustomTypesTest

---

src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java

See vert-x3/vertx-sql-common#34

Added a noarg close method to SQLRowStream

---

src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/asciidoc/kotlin/index.adoc
src/main/asciidoc/ruby/index.adoc
src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCAction.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCAutoCommit.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCBatch.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCallable.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCClose.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCommit.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCExecute.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCQuery.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCRollback.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCUpdate.java
src/main/java/io/vertx/ext/jdbc/impl/actions/StreamQuery.java

Depends on https://github.com/eclipse/vert.x/pull/1869

Use the per-connection explicit task queue as this is what we want

---

src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
src/test/java/io/vertx/ext/jdbc/JDBCClientTest.java

Add a way to expose the native connection

---

src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java
src/test/java/io/vertx/ext/jdbc/JDBCClientTest.java

Depends on https://github.com/vert-x3/vertx-sql-common/pull/40

Implement columns()

---

pom.xml
src/main/java/io/vertx/ext/jdbc/spi/impl/AgroalCPDataSourceProvider.java
src/test/java/io/vertx/ext/jdbc/spi/impl/AgroalCPDataSourceProviderTest.java

@barreiro could you give a review if I'm doing this right?

Initial implementation of the agroal datasource provider

---

src/test/java/io/vertx/ext/jdbc/JDBCStoredProcedureTest.java

should be merged after vert-x3/vertx-sql-common#55

test client call* methods

---

pom.xml
src/main/java/io/vertx/ext/jdbc/spi/impl/AgroalCPDataSourceProvider.java

Nothing special here, just bumping agroal from 0.2 to 1.1

bump agroal to 1.1

---

src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCallable.java

Fixes #135
Fix exception when ResultSet return as out parameter

Convert callable statement out parameter from ResultSet to JSON

---

src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java
src/test/java/io/vertx/ext/jdbc/impl/actions/OptimisticCastTest.java

Signed-off-by: Ruslan Sennov <ruslan.sennov@gmail.com>

more optimisticCast options

---

src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCAction.java

Add java.sql.Statement.setMaxRows(options.getMaxRows())
Motivation:
Add java.sql.Statement.setMaxRows(options.getMaxRows())
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

Add java.sql.Statement.setMaxRows(options.getMaxRows())

---

pom.xml
src/main/java/io/vertx/jdbcclient/impl/actions/JDBCPrepareStatementAction.java
src/main/java/io/vertx/jdbcclient/impl/actions/JDBCPreparedBatch.java
src/main/java/io/vertx/jdbcclient/impl/actions/JDBCPreparedStatement.java
src/main/java/io/vertx/jdbcclient/impl/actions/JDBCQueryAction.java
src/main/java/io/vertx/jdbcclient/impl/actions/JDBCResponse.java
src/test/java/io/vertx/jdbcclient/MSSQLTest.java
src/test/resources/init-mssql.sql

Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Fixes: #199

Fix MSSQL retrieval of generated keys order

---

src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
src/test/java/io/vertx/ThreadLeakCheckerRule.java
src/test/java/io/vertx/ext/jdbc/PoolTest.java

Ported test from #213 to Vert.x 4.0

---

src/main/java/io/vertx/ext/jdbc/JDBCClient.java
src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
src/main/java/io/vertx/ext/jdbc/spi/DataSourceProvider.java
src/main/java/io/vertx/ext/jdbc/spi/impl/AgroalCPDataSourceProvider.java
src/main/java/io/vertx/ext/jdbc/spi/impl/C3P0DataSourceProvider.java
src/main/java/io/vertx/ext/jdbc/spi/impl/HikariCPDataSourceProvider.java
src/main/java/io/vertx/jdbcclient/JDBCPool.java
src/test/java/io/vertx/jdbcclient/JDBCPoolInitTest.java

Create JDBCPool by DataSourceProvider

---

src/main/java/io/vertx/ext/jdbc/impl/actions/CachedParameterMetaData.java
src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCBatch.java

Continues #260
Alternative for #261

fix batch complexity, p.2
