- .gitignore
- pom.xml
- src/main/asciidoc/ruby/index.adoc
- src/main/generated/io/vertx/rxjava/ext/jdbc/JDBCClient.java
- src/main/groovy/io/vertx/groovy/ext/jdbc/JDBCClient.groovy
- src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCStatement.java
- src/main/resources/vertx-jdbc-js/jdbc_client.js
- src/main/resources/vertx-jdbc/jdbc_client.rb
- src/test/java/io/vertx/ext/jdbc/JDBCClientTestBase.java
- src/test/java/io/vertx/ext/jdbc/JDBCTypesTestBase.java
the conversion from JDBC to JSON types was incomplete, this new implementation fixes the issue and add a second DB test server (derby) that would reproduce the issues #16 and #17.
@purplefox @vietj please review.
Also note that the new implementation handles returned dates (DB -> JSON) in the same format as mongo-client for consistency.
> fixes #16 and #17

- pom.xml
- src/test/java/io/vertx/ext/jdbc/JDBCCustomTypesTest.java
This extra test shows that types such as UUID are covered by the fallback mode `toString()`
> add tests showing the fallback mode

- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCUpdate.java
- src/test/java/io/vertx/ext/jdbc/JDBCTypesTestBase.java
jdbc (jtds with sql server and derby) return generated keys that are null or a null generated key resultset if there is no identity column in the table.
The test case was using jtds (1.3.1) to access a table in sql server 2008 where there is NO identity column. In this situation when doing an update, jtds returns null generatedKeys. The JDBCUpdate code was attempting to add the null key to the JsonArray and throwing an exception.
This proposed fix just discards the null key and also works if the returned result set is null.
Tested and works fine.
Unit test now included.
I hope this is acceptable.
> discard null generated keys to prevent exception

- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java
- src/test/java/io/vertx/ext/jdbc/JDBCStoredProcedureTest.java
fixes vert-x3/vertx-sql-common#18: allow INOUT args on stored procedures
> fix vert-x3/vertx-sql-common#18: allow INOUT args on stored procedures

- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java
- src/test/java/io/vertx/ext/jdbc/JDBCClientTestBase.java
- src/test/java/io/vertx/ext/jdbc/JDBCCustomTypesTest.java
- src/test/java/io/vertx/ext/jdbc/impl/actions/OptimisticCastTest.java
- src/test/java/io/vertx/ext/jdbc/impl/actions/SQLConvertTest.java
Fixes vert-x3/vertx-sql-common#19
Implemented a optimistic cast for JDBC types for now it decodes, temporal types plus UUID
> Fixes vert-x3/vertx-sql-common#19: implement optimistic casting for temporal and UUID types in JDBC

- src/main/java/io/vertx/ext/jdbc/spi/impl/HikariCPDataSourceProvider.java
- src/test/java/io/vertx/ext/jdbc/spi/impl/HikariCPDataSourceProviderTest.java
Hi.
I've fixed a small bug of HikariCPDataSourceProvider.
When we use leakDetectionThreshold, it will fail due to ClassCastException.
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
```
> Fix HikariCPDataSourceProvider

- src/main/asciidoc/java/index.adoc
- src/main/java/io/vertx/ext/jdbc/package-info.java
The documentation refers to setting "UUIDCast" in the JSON config object but the extension actually uses "castUUID". See the JDBCStatementHelper.java
```
public JDBCStatementHelper(JsonObject config) {
this.castUUID = config.getBoolean("castUUID", false);
}
```
> Correct "UUIDCast" to "castUUID"

- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCStatementHelper.java
- src/test/java/io/vertx/ext/jdbc/impl/actions/SQLConvertTest.java
An Instant may carry submillisecond data. So when it is added to Json, this information is reflected in the String conversion.
But the current regular expression in JDBCStatementHelper only allows for milliseconds precision.
Consequently, the value is not even identified as a timestamp, but as a String.
In addition to that, the current from/to SQL conversion methods simply erase submillisecond data, even though it's supported in the java.sql.Timestamp format.
SQLConvertTest has been updated with more test cases. Also it's been fixed because if something wasn't properly detected, it was simply returned as String and of course was equal to the original.
> Fixes Instant/Timestamp conversion

- src/main/asciidoc/groovy/index.adoc
- src/main/asciidoc/java/index.adoc
- src/main/asciidoc/js/index.adoc
- src/main/asciidoc/kotlin/index.adoc
- src/main/asciidoc/ruby/index.adoc
- src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
- src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/StreamQuery.java
- src/main/java/io/vertx/ext/jdbc/package-info.java
- src/test/java/io/vertx/ext/jdbc/JDBCClientTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCClientTestBase.java
In current `SQLRowStream` implementation every row fetched in own `worker.executeBlocking()` method. This patch introduces internal accumulator to read batch of rows in one time. On my computer fetching of 2M rows runs 10x faster. All tests (including pause/resume) passes.
@pmlopes please review
> RowStream accumulator

- src/main/java/examples/JDBCExamples.java
- src/main/java/io/vertx/ext/jdbc/JDBCClient.java
- src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
- src/test/java/io/vertx/ext/jdbc/CloseTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCBatchTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCClientTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCCustomTXIsolationTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCCustomTypesTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCPoolMetricsTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCQueryTimeoutTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCStoredProcedure2Test.java
- src/test/java/io/vertx/ext/jdbc/JDBCStoredProcedureTest.java
- src/test/java/io/vertx/ext/jdbc/JDBCTypesTestBase.java
- src/test/java/io/vertx/ext/jdbc/RefCountTest.java
- src/test/java/io/vertx/ext/jdbc/SharedClientTest.java
This PR will share client interface `SQLClient` as same as `SQLConnection` derived from common interfaces in this PR [#46](https://github.com/vert-x3/vertx-sql-common/pull/46) I think this will be major change.
> Common SQLClient interface with implementation

- src/test/java/io/vertx/ext/jdbc/CloseConnectionChecker.java
- src/test/java/io/vertx/ext/jdbc/JDBCClientTest.java
blocked by vert-x3/vertx-sql-common#58
> queryStream* one-shot tests

- src/main/asciidoc/index.adoc
- src/main/java/io/vertx/ext/jdbc/spi/impl/BoneCPDataSourceProvider.java
BoneCP has been deprecated upstream, this PR deprecates it in this module so we will perform cleanup on the next major release.
> Deprecate BoneCP

- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java
> Use column labels instead of column names for SQLRowStream.columns()

- pom.xml
For details, see [release notes of c3p0 v0.9.5.4](https://github.com/swaldman/c3p0/blob/c3p0-0.9.5.4/src/dist-static/RELEASE_NOTES-c3p0-0.9.5.4)
Summary of the fix:
> CVE-2018-20433, https://nvd.nist.gov/vuln/detail/CVE-2018-20433
>     
>   The c3p0 parsed XML config files liberally, including resolving external
>   entity references. Incautious use of this feature could permit injection
>   of malicious config. Now c3p0 does not resolve external entity references
>   in its the XML config file.
(cherry picked from commit 55bf8ad1659820fb6f4e195aee7c111dc7d219ef)
> fix: use c3P0 v0.9.5.4 to prevent DoS vulnerability. 

- pom.xml
For details, see [release notes of c3p0 v0.9.5.4](https://github.com/swaldman/c3p0/blob/c3p0-0.9.5.4/src/dist-static/RELEASE_NOTES-c3p0-0.9.5.4)
Summary of the fix:
> CVE-2018-20433, https://nvd.nist.gov/vuln/detail/CVE-2018-20433
>     
>   The c3p0 parsed XML config files liberally, including resolving external
>   entity references. Incautious use of this feature could permit injection
>   of malicious config. Now c3p0 does not resolve external entity references
>   in its the XML config file.
> fix: update c3P0 dependency to v0.9.5.4 to prevent DoS vulnerability. 

- src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
- src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCAction.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCAutoCommit.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCBatch.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCallable.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCClose.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCCommit.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCExecute.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCQuery.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCRollback.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCUpdate.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/StreamQuery.java
This makes the code easier to reason about (in particular threading)
These are no longer needed as we can now use the serialization provided by executeBlocking on the context bound to the JDBCConnectionImpl instance.
Now it gets a connection then schedules execution on the worker pool.
Previously the operation was executed on the thread that acquires connections (thus serializing all operations on this JDBC client instance).
Also, this avoids to duplicate metrics and connection management (and tracing in the future).
> Refactored JDBC action scheduling

- src/main/java/io/vertx/jdbcclient/impl/actions/JDBCPreparedQuery.java
- src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java
This change fixes issue #210 since the handling of Buffer parameters in prepared statements is currently broken.
1. When writing t a Blob the first position is 1.
2. Blob.setBytes() is not a fluent API and returns the number of written bytes.
Additionally the changes adds a regression test.
> Address issue #210 - Fix for handling of Buffer parameters in prepared statements

- src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
- src/test/java/io/vertx/ext/jdbc/PoolTest.java
Fixes #164
Previously, direct queries execution was serialized on the thread that acquires connection.
> Use all connections in pool when executing direct queries

- src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/StreamQuery.java
- src/test/java/io/vertx/it/MSSQLJDBCParallelTest.java
- src/test/java/io/vertx/it/MSSQLParallelTest.java
- src/test/java/io/vertx/it/MSSQLTest.java
- src/test/java/io/vertx/it/MSSQLTestBase.java
Signed-off-by: Olga Ivanova <olga.a.ivanova@inbox.ru>
Motivation:
Fix my issue https://github.com/vert-x3/vertx-jdbc-client/issues/217
The problem was in using same queue for different connections (in ContextImpl.executeBlocking).
> add statements queue to connection && row stream

- src/main/java/io/vertx/jdbcclient/impl/JDBCPoolImpl.java
- src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java
This change fixes #226 since the closing of connections for failing queries created by JDBCPool.query(...) or JDBCPool.preparedQuery(...) is currently broken.
Additionally adds according regression tests to JDBCPoolTest.
> Address issue #226 - Fix for missing close of connection when query fails

- src/main/java/io/vertx/jdbcclient/impl/actions/JDBCColumnDescriptor.java
- src/main/java/io/vertx/jdbcclient/impl/actions/JDBCQueryAction.java
- src/test/java/io/vertx/jdbcclient/JDBCPoolColumnDescTest.java
Closes #225
The Sql Client implementation for JDBC was missing result set metadata inspection to build column descriptors.
> Implement JDBC Pool ColumnDescriptor

- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCTypeProvider.java
- src/test/java/io/vertx/jdbcclient/JDBCPoolColumnDescOracleExtTest.java
Fixes #248
Some databases drivers (in this example, Oracle) use unknown type number which makes `JDBCType.valueOf()` throw `IllegalArgumentException`.
This commit adds a `find()` method to `JDBCTypeProvider` which, instead of failing, returns `JDBCType.OTHER` when type number is unknown.
> Avoid failure when vendor type number is unknown

- src/test/java/io/vertx/ext/jdbc/PoolTest.java
Hi,
This PR fixes 1 violations of [Sonar Rule 2142: '"InterruptedException" should not be ignored'](https://rules.sonarsource.com/java/RSPEC-2142). This is done without introducing any new violations of Sonar rules.
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2142](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#interruptedexception-should-not-be-ignored-sonar-rule-2142).
P.S.: Note that this PR is not created/submitted by a bot. If you have any feedback, please leave them as comments.
> Fix violations of Sonar rule 2142

- src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCAction.java
- src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCBatch.java
When executing a batch request, the number of `getParameterMetaData()` calls increases linearly with the number of placeholders in the request. For some drivers (at least for postgre), this dramatically affects query execution time.
> fix batch complexity

- src/main/java/examples/JDBCTypeExamples.java
The documentation on the website contains invalid code snippets:
https://vertx.io/docs/vertx-jdbc-client/java/#_data_types
It seems `JDBCTypeExamples.java` misses the `@Sample` annotation from the `vertx-docgen` project. This pull request adds this annotation.
I tested the doc generation with this change and the snippets are correctly included.
> Add missing @Source annotation to all examples

- src/main/java/io/vertx/jdbcclient/impl/JDBCRow.java
- src/test/java/io/vertx/jdbcclient/OracleRowIdTest.java
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
Fix #269 
Row Id's are returned as byte arrays by the driver. Writting, on the other hand writting can use String as shown on the official oracle jdbc manual:
https://docs.oracle.com/cd/A57673_01/DOC/server/doc/A56282_01/toc.htm#421162
> Fix JDBC row getter

- src/main/java/io/vertx/jdbcclient/impl/ConnectionImpl.java
Otherwise, the callbacks might be invoked in unexpected order
Related to https://github.com/eclipse-vertx/vert.x/issues/4446
> Do not mix Future terminal operations with other operations

- src/main/asciidoc/index.adoc
- src/main/java/examples/JDBCSqlClientExamples.java
- src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
- src/main/java/io/vertx/ext/jdbc/spi/DataSourceProvider.java
- src/main/java/io/vertx/jdbcclient/JDBCPool.java
- src/test/java/io/vertx/it/ClickHouseOldAPITest.java
- src/test/java/io/vertx/jdbcclient/JDBCPoolInitTest.java
Motivation:
With the old JDBC Client API it was possible to configure the data source name, but this option is not available when using JDBCPool that wraps the old JDBCClient into the new SQL Client API.
Instead, a random UUID is always used as the data source name. This causes a lot of problems with metrics such as:
a) It's impossible to know which data source the random UUID maps to. This can be a problem with projects using multiple data sources to different databases.
b) The data source names change on each deployment, which makes it impossible to follow trends over time.
c) Can add to the operating costs when there are a huge amount of servers when using e.g. CloudWatch which is billed per metric.
Conformance:
Your commits should be signed and you should have signed the Eclipse …
> Make data source name configurable through JDBCPool

- src/test/java/io/vertx/it/ClickHouseOldAPITest.java
- src/test/java/io/vertx/it/ClickHouseTest.java
Motivation:
ClickHouseOldAPITest is timing out on CI
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
> Fix ClickHouseOldAPITest timeout on CI

- src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java
- src/main/java/io/vertx/ext/jdbc/impl/JDBCConnectionImpl.java
- src/main/java/io/vertx/jdbcclient/JDBCPool.java
- src/main/java/io/vertx/jdbcclient/impl/ConnectionImpl.java
- src/test/java/io/vertx/ext/jdbc/JDBCClientTestBase.java
- src/test/java/io/vertx/jdbcclient/JDBCTracingTest.java
The tracing integration is broken because it requires to use the server socket address to report tracing information and the JDBC API does not naturally provides it.
We should try to determine the server address with a best effort to allow proper tracing reporting.
> Fix tracing integration with JDBC SQL client

- src/main/java/io/vertx/jdbcclient/JDBCPool.java
Original report in https://github.com/eclipse-vertx/vertx-sql-client/issues/1527
The datasource will be named after {@link PoolOptions#getName()}, even though the Javadoc in this class indicates that the name is only used when the {@link Pool} is shared.
> Documentation: PoolOptions.getName is used to name the JDBC datasource
